name: content-for-spring-framework-61
base: bare
build-base: core22
version: '6.1.8'
summary: Rebuild of Spring Boot Framework source
license: Apache-2.0
description: |
  Rebuild of Spring® Framework version 6.1.8.

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.

grade: devel
confinement: strict

parts:
  spring-framework:
    plugin: nil
    source: https://github.com/spring-projects/spring-framework/
    source-type: git
    source-tag: v6.1.8
    build-packages:
      - openjdk-17-jdk-headless
    override-build: |
      mkdir -p $HOME/.gradle
      echo 'systemProp.user.name=spring-builds+github' >> $HOME/.gradle/gradle.properties
      echo 'systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=4' >> $HOME/.gradle/gradle.properties
      ./gradlew -PdeploymentRepository=$CRAFT_PART_BUILD/deployment-repository build publishAllPublicationsToDeploymentRepository
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/maven-repo
      cp -r $CRAFT_PART_BUILD/deployment-repository/* $CRAFT_PART_INSTALL/maven-repo
      craftctl default
