name: content-for-spring-boot-runtime-33
base: bare
build-base: core22
version: '3.3.5'
summary: Rebuild of Spring® Boot Framework source
license: Apache-2.0
description: |
  Rebuild of Spring® Boot version 3.3.4.

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.


grade: devel
confinement: strict

parts:
  spring-boot:
    plugin: nil
    source: https://github.com/spring-projects/spring-boot/
    source-type: git
    source-tag: v3.3.5
    build-packages:
      - openjdk-17-jdk-headless
    override-build: |
      mkdir -p $HOME/.gradle
      echo 'systemProp.user.name=spring-builds+github' >> $HOME/.gradle/gradle.properties
      echo 'systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=4' >> $HOME/.gradle/gradle.properties
      ./gradlew -PdeploymentRepository=$CRAFT_PART_INSTALL/maven-repo build publishAllPublicationsToDeploymentRepository

  add-cache:
    after:
      - spring-boot
    plugin: nil
    source-type: local
    source: .
    override-build: |
      python3 clone-deps.py $HOME/.gradle/ $CRAFT_PART_INSTALL/maven-repo
