name: content-for-spring-boot-runtime-33
base: bare
build-base: core22
version: '3.3.5'
summary: Rebuild of Spring® Boot Framework sources
license: Apache-2.0
description: |
  Rebuild of Spring® Boot sources.

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.


grade: devel
confinement: strict

parts:
  gradle-init:
    plugin: nil
    source: .
    override-build: |
      cp init.gradle $CRAFT_STAGE/

  spring-boot:
    after:
      - gradle-init
    plugin: nil
    source: https://github.com/spring-projects/spring-boot/
    source-type: git
    source-tag: v3.3.8
    build-packages:
      - openjdk-17-jdk-headless
    override-build: |
      mkdir -p $HOME/.gradle
      echo 'systemProp.user.name=spring-builds+github' >> $HOME/.gradle/gradle.properties
      echo 'systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      echo 'org.gradle.daemon=4' >> $HOME/.gradle/gradle.properties
      ./gradlew --init-script=$CRAFT_STAGE/init.gradle -PdeploymentRepository=$CRAFT_PART_INSTALL/maven-repo build publishAllPublicationsToDeploymentRepository
