name: devpack-for-spring
base: core22
version: '0.05'
summary: Development tools for Spring® projects
license: Apache-2.0
description: |
  Development tools for Spring® projects.

  The snap packages spring-cli and spring-boot-cli.
  The snap provides an utility to install binaries of Spring projects rebuilds.

  Snap documentation:
  https://github.com/vpa1977/spring-boot-snap/blob/main/devpack-for-spring/README.md

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  installer:
    plugin: nil
    source: configure
    build-packages:
      - openjdk-17-jdk-headless
      - maven
    override-build: |
      mvn package
      craftctl default
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/manifest
      cp $SNAPCRAFT_PROJECT_DIR/manifest/manifest.yaml $CRAFT_PART_INSTALL/manifest
      mkdir -p $CRAFT_PART_INSTALL/install
      cp $CRAFT_PART_BUILD/target/configure-1.0-shaded.jar $CRAFT_PART_INSTALL/install/
      chmod +x $CRAFT_PART_INSTALL/install/configure-1.0-shaded.jar
      craftctl default

  spring-cli:
    plugin: nil
    source: https://github.com/spring-projects/spring-cli
    source-type: git
    source-tag: v0.8.1
    build-packages:
      - openjdk-17-jdk-headless
    override-build: |
      ./gradlew build -x test
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/spring-cli
      cp $CRAFT_PART_BUILD/build/libs/spring-cli-0.8.1.jar $CRAFT_PART_INSTALL/spring-cli
      cp $CRAFT_PROJECT_DIR/run-spring-cli.sh $CRAFT_PART_INSTALL/spring-cli
      craftctl default

  spring-boot-cli:
    plugin: nil
    source: https://github.com/spring-projects/spring-boot
    source-type: git
    source-tag: v3.2.4
    build-packages:
      - openjdk-17-jdk-headless
      - tar
    override-build: |
      cd spring-boot-project/spring-boot-tools/spring-boot-cli/ && ../../../gradlew publish
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/spring-boot-cli
      tar xvf $CRAFT_PART_BUILD/spring-boot-project/spring-boot-tools/spring-boot-cli/build/distributions/spring-boot-cli-3.2.4-bin.tar.gz --strip-components 1 -C $CRAFT_PART_INSTALL/spring-boot-cli
      craftctl default

  rockcraft:
    plugin: nil
    stage-snaps:
      - rockcraft

apps:
  install:
    command: install/configure-1.0-shaded.jar

  spring-boot-cli:
    command: spring-boot-cli/bin/spring

  spring-cli:
    command: spring-cli/run-spring-cli.sh
