name: spring-boot
base: core22
version: '0.01'
summary: Spring Boot framework development tools
description: |
  Spring boot framework development tools

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:

  cache:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp $CRAFT_PROJECT_DIR/build-springboot.sh $CRAFT_PART_INSTALL/usr/bin

  spring-cli:
    plugin: nil
    source: https://github.com/spring-projects/spring-cli
    source-type: git
    source-tag: v0.8.1
    build-packages:
      - openjdk-17-jdk-headless
    override-build: |
      ./gradlew build -x test
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/spring-cli
      cp $CRAFT_PART_BUILD/build/libs/spring-cli-0.8.1.jar $CRAFT_PART_INSTALL/spring-cli
      cp $CRAFT_PROJECT_DIR/run-spring-cli.sh $CRAFT_PART_INSTALL/spring-cli
      craftctl default

  spring-boot-cli:
    plugin: nil
    source: https://github.com/spring-projects/spring-boot
    source-type: git
    source-tag: v3.2.4
    build-packages:
      - openjdk-17-jdk-headless
      - tar
    override-build: |
      cd spring-boot-project/spring-boot-tools/spring-boot-cli/ && ../../../gradlew publish
    override-stage: |
      mkdir -p $CRAFT_PART_INSTALL/spring-boot-cli
      tar xvf $CRAFT_PART_BUILD/spring-boot-project/spring-boot-tools/spring-boot-cli/build/distributions/spring-boot-cli-3.2.4-bin.tar.gz --strip-components 1 -C $CRAFT_PART_INSTALL/spring-boot-cli
      craftctl default

apps:
#  cache:
#    command: usr/bin/build-springboot.sh

  spring-boot-cli:
    command: spring-boot-cli/bin/spring

  spring-cli:
    command: spring-cli/run-spring-cli.sh
